profile = "user"
changelog-seen = 2

[llvm]
download-ci-llvm = true

[build]
host = ["x86_64-unknown-linux-gnu"]
target = ["x86_64-unknown-linux-gnu", "x86_64-unknown-daisogen"]

[rust]
incremental = true
